version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://guest:password@postgres_db/my-db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
